title: GitHub Learning Lab
tagline: A brand new course on Learning Lab
description: GitHub Learning Lab excercise
template:
  repo: github-learning-lab-template
  name: github-learning-lab
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
